---
- name: Upgrade Packages
  dnf:
    name: "*"
    state: latest
    update_cache: true
  register: update_packages
  when:
    - not test_mode

- name: disable default MySQL
  shell: yum module disable mysql -y
  args:
    warn: false

- name: Install Packages
  dnf:
    name:
      - "@Development tools"
      - rsync
      - git
      - zip
      - unzip
      - vim
      - htop
      - vnstat
      - tmux
      - mc
      - mysql-community-client
      - cups
      - ghostscript
      # - ghostscript-cups
      - duplicity
      - clamav
      - clamav-update
      - yum-utils
      - dnf-utils
      - dnf-plugins-core
      - telnet
      - screen
      - wget
      - dkms
      - libselinux
      - libselinux-utils
      # - libselinux-python
      - libsemanage
      - python3-libsemanage
    state: present
    update_cache: true
