---
- name: selinux - httpd
  selinux_permissive:
    name: httpd_t
    permissive: true
# when: '"amazon" in ansible_product_version'

- name: selinux - http network connection
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: selinux - http database connection
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

- name: selinux - http send mail
  seboolean:
    name: httpd_can_sendmail
    state: true
    persistent: true

- name: selinux - http connect ldap
  seboolean:
    name: httpd_can_connect_ldap
    state: true
    persistent: true

- name: selinux - http connect nfs
  seboolean:
    name: httpd_use_nfs
    state: true
    persistent: true

- name: selinux - antivirus
  seboolean:
    name: antivirus_can_scan_system
    state: true
    persistent: true
