---
- name: unoconv - Packages
  dnf:
    name:
      - libreoffice-core
      - libreoffice-pyuno
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk-headless
    state: present

# Alternative? https://centos.pkgs.org/8/epel-x86_64/unoconv-0.9.0-2.el8.noarch.rpm.html
- name: unoconv - download
  git:
    repo: git://github.com/dagwieers/unoconv.git
    dest: /opt/unoconv
    version: 0.9.0

- name: unoconv -  symbolic link
  file:
    src: /opt/unoconv/unoconv
    dest: /usr/bin/unoconv
    state: link

- name: unoconv - config
  template:
    src: unoconv.service
    dest: /etc/systemd/system/unoconv.service
    mode: 0644

- name: unoconv - start service
  service:
    name: unoconv
    enabled: true
    state: started

- name: unoconv - selinux
  seboolean:
    name: httpd_execmem
    state: true
    persistent: true
  when:
    - not test_mode
