---
- hosts: all
  become: true
  become_user: root

  roles:
    # - dev-sec.os-hardening
    - lms

  tasks:
    - name: data folder
      file:
        path: "{{ data_folder }}"
        state: directory
        mode: 0755
