---
- hosts: all
  become: true
  become_user: root

  # roles:
  #   - lms

  tasks:
    - name: Include dev-sec.os-hardening role
      include_role:
        name: dev-sec.os-hardening
      when: not test_mode

    - name: Include LMS role
      include_role:
        name: lms
